// ? Generated by https://jvilk.com/MakeTypes/.

export interface IGetPlaylists {
  href: string;
  items?: IPlaylist[] | null;
  limit: number;
  next?: null;
  offset: number;
  previous?: null;
  total: number;
}

export interface IPlaylist {
  collaborative: boolean;
  external_urls: IExternalUrls;
  href: string;
  id: string;
  images?: IImage[] | null;
  name: string;
  owner: IOwner;
  primary_color?: null;
  public: boolean;
  snapshot_id: string;
  tracks: ITracksInfo;
  type: string;
  uri: string;
}

export interface IExternalUrls {
  spotify: string;
}

export interface IImage {
  height?: number | null;
  url: string;
  width?: number | null;
}

export interface IOwner {
  display_name: string;
  external_urls: IExternalUrls;
  href: string;
  id: string;
  type: string;
  uri: string;
}

export interface ITracksInfo {
  href: string;
  total: number;
}

export interface IGetTracks {
  href: string;
  items?: ITrack[] | null;
  limit: number;
  next: string;
  offset: number;
  previous?: null;
  total: number;
}

export interface ITrack {
  added_at: string;
  added_by: IAddedBy;
  is_local: boolean;
  primary_color?: null;
  track: ITrackInfo;
  video_thumbnail: IVideoThumbnail;
}

export interface IAddedBy {
  external_urls: IExternalUrls;
  href: string;
  id: string;
  type: string;
  uri: string;
}

export interface ITrackInfo {
  album: IAlbum;
  artists?: IArtist[] | null;
  available_markets?: Array<string | null> | null;
  disc_number: number;
  duration_ms: number;
  episode: boolean;
  explicit: boolean;
  external_ids: IExternalIds;
  external_urls: IExternalUrls;
  href: string;
  id: string;
  is_local: boolean;
  name: string;
  popularity: number;
  preview_url?: string | null;
  track: boolean;
  track_number: number;
  type: string;
  uri: string;
}

export interface IAlbum {
  album_type: string;
  artists?: IArtist[] | null;
  available_markets?: Array<string | null> | null;
  external_urls: IExternalUrls;
  href: string;
  id: string;
  images?: IImage[] | null;
  name: string;
  release_date: string;
  release_date_precision: string;
  total_tracks: number;
  type: string;
  uri: string;
}

export interface IArtist {
  external_urls: IExternalUrls;
  href: string;
  id: string;
  name: string;
  type: string;
  uri: string;
}

export interface IExternalIds {
  isrc: string;
}

export interface IVideoThumbnail {
  url?: null;
}

export interface IGetDevices {
  devices?: IDevice[] | null;
}
export interface IDevice {
  id: string;
  is_active: boolean;
  is_private_session: boolean;
  is_restricted: boolean;
  name: string;
  type: string;
  volume_percent: number;
}
