// ? Generated by https://jvilk.com/MakeTypes/.

export interface GetPlaylists {
  href: string;
  items?: Playlist[] | null;
  limit: number;
  next?: null;
  offset: number;
  previous?: null;
  total: number;
}

export interface Playlist {
  collaborative: boolean;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  images?: Image[] | null;
  name: string;
  owner: Owner;
  primary_color?: null;
  public: boolean;
  snapshot_id: string;
  tracks: TracksInfo;
  type: string;
  uri: string;
}

export interface ExternalUrls {
  spotify: string;
}

export interface Image {
  height?: number | null;
  url: string;
  width?: number | null;
}

export interface Owner {
  display_name: string;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  type: string;
  uri: string;
}

export interface TracksInfo {
  href: string;
  total: number;
}

export interface GetTracks {
  href: string;
  items?: Track[] | null;
  limit: number;
  next: string;
  offset: number;
  previous?: null;
  total: number;
}

export interface Track {
  added_at: string;
  added_by: AddedBy;
  is_local: boolean;
  primary_color?: null;
  track: TrackInfo;
  video_thumbnail: VideoThumbnail;
}

export interface AddedBy {
  external_urls: ExternalUrls;
  href: string;
  id: string;
  type: string;
  uri: string;
}

export interface TrackInfo {
  album: Album;
  artists?: Artist[] | null;
  available_markets?: Array<string | null> | null;
  disc_number: number;
  duration_ms: number;
  episode: boolean;
  explicit: boolean;
  external_ids: ExternalIds;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  is_local: boolean;
  name: string;
  popularity: number;
  preview_url?: string | null;
  track: boolean;
  track_number: number;
  type: string;
  uri: string;
}

export interface Album {
  album_type: string;
  artists?: Artist[] | null;
  available_markets?: Array<string | null> | null;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  images?: Image[] | null;
  name: string;
  release_date: string;
  release_date_precision: string;
  total_tracks: number;
  type: string;
  uri: string;
}

export interface Artist {
  external_urls: ExternalUrls;
  href: string;
  id: string;
  name: string;
  type: string;
  uri: string;
}

export interface ExternalIds {
  isrc: string;
}

export interface VideoThumbnail {
  url?: null;
}

export interface GetDevices {
  devices?: Device[] | null;
}
export interface Device {
  id: string;
  is_active: boolean;
  is_private_session: boolean;
  is_restricted: boolean;
  name: string;
  type: string;
  volume_percent: number;
}

export interface Search {
  tracks: GetTracks;
}

export interface GetMe {
  display_name: string;
  external_urls: ExternalUrls;
  followers: Followers;
  href: string;
  id: string;
  images?: null[] | null;
  type: string;
  uri: string;
}

export interface Followers {
  href?: null;
  total: number;
}

export interface GetPlayer {
  device: Device;
  shuffle_state: boolean;
  repeat_state: string;
  timestamp: number;
  context: Context;
  progress_ms: number;
  item: Player;
  currently_playing_type: string;
  actions: Actions;
  is_playing: boolean;
}


export interface Player {
  album: Album;
  artists?: Artist[] | null;
  disc_number: number;
  duration_ms: number;
  explicit: boolean;
  external_ids: ExternalIds;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  is_local: boolean;
  is_playable: boolean;
  linked_from: LinkedFrom;
  name: string;
  popularity: number;
  preview_url: string;
  track_number: number;
  type: string;
  uri: string;
}


export interface Context {
  external_urls: ExternalUrls;
  href: string;
  type: string;
  uri: string;
}

export interface LinkedFrom {
  external_urls: ExternalUrls;
  href: string;
  id: string;
  type: string;
  uri: string;
}
export interface Actions {
  disallows: Disallows;
}
export interface Disallows {
  resuming: boolean;
  skipping_prev: boolean;
}

